### ISSUE TITLE
Test breaking locally, travis passed

### ISSUE THREAD

**Issue by greenitthe** [unioncollege-webtech/fizzbuzz#5]
@barberboy 
Referencing #4 

Running `node fizzbuzz.js`, output looks correct. Though travis test passed, running test on desktop breaks with:

> assert.js:89
>   throw new assert.AssertionError({
>   ^
> ' on line 1.ror: Expected '1' to be '1
>     at C:\Users\James\Documents\GitHub\fizzbuzz\test\index.js:21:20
>     at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:380:3)

**Comment by keawade** [comment]
I had the same issue with the local tests.
